[features]
seeds = false
skip-lint = false

[programs.devnet]
mmoshforge = "FAtrNioZaqBBa9YAXK1Q2ijEGvh44Wpoqpx2gRXN1Q4b"

[registry]
url = "https://api.apr.dev"


[provider]
cluster = "devnet"
wallet = "/Users/jeyakumar/JEYAKUMAR/ssh/hellbender/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/sop.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/mintingMemberShip.ts"
