[features]
seeds = false
skip-lint = false

[programs.mainnet]
mmoshforge = "GQJBSNqckwApKwrjHMgvhhFtwZFxb3YCoDFFcLmYCnEA"

[registry]
url = "https://api.apr.dev"


[provider]
cluster = "mainnet"
wallet = "/Users/jeyakumar/JEYAKUMAR/ssh/hellbender/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/sop.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/mintingMemberShip.ts"
