[features]
seeds = false
skip-lint = false

#[programs.devnet]
[programs.localnet]
sop = "62toyp2z8hsx3xj1Mx2vHMdsXMfgxTCvJ1tT6BehXpxF"

[registry]
url = "https://api.apr.dev"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "target/deploy/mpl_token_metadata.so"

[provider]
# cluster = "devnet"
cluster = "Localnet"
wallet = "/Users/jeyakumar/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/sop.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/mintingMemberShip.ts"
