[features]
seeds = false
skip-lint = false

[programs.mainnet]
sop = "62toyp2z8hsx3xj1Mx2vHMdsXMfgxTCvJ1tT6BehXpxF"

[registry]
url = "https://api.apr.dev"


[provider]
cluster = "mainnet"
wallet = "/Users/jeyakumar/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/sop.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/mintingMemberShip.ts"
