[toolchain]

[features]
resolution = false
seeds = false
skip-lint = false

[programs.devnet]
mmoshforge = "EY88TjZfEHkJBq4DoYqZPLEvBTT1YEPAKXWXD531dHmN"

[registry]
url = "https://api.apr.dev"


[provider]
cluster = "devnet"
wallet = "/Users/jeyakumar/JEYAKUMAR/ssh/hellbender/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/sop.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/mintingMemberShip.ts"
